services:
  traefik:
    image: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.file.directory=/etc/traefik/services"
      - "--entrypoints.web.address=:${PORT}"
    environment:
      - APP_URL=${APP_URL}
    volumes:
      - ./services:/etc/traefik/services
    network_mode: "host"